version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: awsome_prompt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/02_data.sql

  backend:
    build: ../backend
    restart: on-failure
    ports:
      - "50051:50051"
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/awsome_prompt?sslmode=disable
    depends_on:
      - postgres

  frontend:
    build: ../frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  envoy:
    image: envoyproxy/envoy:v1.25-latest
    ports:
      - "80:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
